#ifndef PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_
#define PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_

typedef enum {
  OK,
  INCORRECT_ARGS,
  INPUT_ERROR,
  ALLOCATION_ERROR,
} return_code_t;

#endif  // PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_
