#ifndef TP_C_CPP_PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_
#define TP_C_CPP_PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_

typedef enum {
  OK,
  INCORRECT_ARGS,
  INPUT_ERROR,
  ALLOCATION_ERROR,
} return_code_t;

#endif  // TP_C_CPP_PROJECT_AIRCRAFTS_LIB_RETURN_CODES_H_
