#ifndef TP_C_CPP_PROJECT_POSTS_LIB_INC_RETURN_CODES_H_
#define TP_C_CPP_PROJECT_POSTS_LIB_INC_RETURN_CODES_H_

typedef enum {
  OK,
  INCORRECT_ARGS,
  INPUT_ERROR,
  ALLOCATION_ERROR,
  KEY_ERROR,
  FILE_ERROR,
  CALL_HELP,
  PARALLEL_ERROR
} return_code_t;

void check_error(int rc);

#endif  // TP_C_CPP_PROJECT_POSTS_LIB_INC_RETURN_CODES_H_
